### PR TITLE
#336 Message notification are localized

### PR DESCRIPTION
**Pull request by MLE-Astek**
Warning, there dependency to Java-Spring-Integration project in SNAPSHOT => to modify before merging

### CODE REVIEW

**Comment by bobeal** [comment]
* I still see notifications messages in english (see attached screenshot)
* In the commit, I saw nothing about translating actions labels
* More generally, please avoid adding noise in commits with some code refactorings (and branch names starting with a # are not very command-line friendly)

screen shot 2015-11-29 at 08 56 49

**Comment by tbroyer** [comment]
> I still see notifications messages in english

I suppose it could have to do with the fact the Kernel uses `fr-FR` and the Portal `fr`, and the Portal doesn't do a "proper locale match" (see ozwillo/ozwillo-kernel@d091d675de809e5ad752bad5241d52e27b1b89d0 for how I fixed a similar issue on Kernel side).
I could possibly change the Kernel to use `fr` (as it's effectively an equivalent to `fr-FR`) for the notifications it emits, but that wouldn't change anything for notifications emitted by applications, which could very well use `fr-FR` (BTW, they could also use `fr-BE` and we'd like to match it to French if there's no `fr` or `fr-FR` localized value).

**Comment by MLE-Astek** [comment]
I have test the fix and it work for me … have you take the newest version of Java-spring-integration ? There some essential modifications in https://github.com/ozwillo/ozwillo-java-spring-integration/commit/776008687402151500d77f47a6739c513bd22aa9. And with this line we have the localized message (UserNotificationResponse, line 222)
```
notification.getMessage(locale)
```

For the "noise" in commit it's just [the boy's scout rule] (http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule) "Always leave the campground cleaner than you found it.", and i do only the most visible. Well it's only if we want improve the code quality.

Ok to not put "#" at the beginning of commit message

@tbroyer : I will see your commit

**Comment by bobeal** [comment]
Hi @MLE-Astek 

* Yes, I have the last version of Spring integration library (for instance, I see the "Discard unknown property" logs added in UserNotificationResponse)
* As @tbroyer pointed out, this is a « locale name » mismatch. For me, « locale.toLanguageTag() » return « fr » (and not « FR-fr »), thus explaining I don't see the French messages
* I have (almost) no problem with boy scouts. My concern is about the atomicity of git commits (one commit == one concern / issue / task). Code quality can (must !) be improved (when it's time to do so) ... but in separate commits.

**Comment by MLE-Astek** [comment]
Ok, for atomicity, i will do that.
For you local i will look that deeper

**Comment by tbroyer** [comment]
FWIW, I just pushed a commit on the Kernel that would now match `fr-LU` or `fr` to `fr-FR` for example (and the root locale to some English flavor): ozwillo/ozwillo-kernel@639f0df53e2082c5487987c5c2296369d0d9c6a5
Maybe you could draw inspiration from it for the Portal (which arguably has more needs for proper i18n than the Kernel).

**Comment by MLE-Astek** [comment]
I've make some modification in [java-spring-integration] (https://github.com/ozwillo/ozwillo-java-spring-integration/commit/9bc6272eb3e11039f788389a63835e2e9e942c61) to improve the detection of acceptable language.

**Pull request merged**
